package com.igor.briskofmagic.enchantment;

import com.igor.briskofmagic.BriskofMagic;
import com.igor.briskofmagic.enchantment.custom.BufferEnchantmentEffect;
import com.igor.briskofmagic.enchantment.custom.FieryEnchantmentEffect;
import com.igor.briskofmagic.enchantment.custom.FrostbiteEnchantmentEffect;
import net.minecraft.advancements.critereon.*;
import net.minecraft.core.HolderSet;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.models.blockstates.Condition;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.*;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.EquipmentSlotGroup;
import net.minecraft.world.entity.ai.attributes.Attribute;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.item.enchantment.*;
import net.minecraft.world.item.enchantment.effects.*;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.dimension.DimensionType;
import net.minecraft.world.level.material.Fluids;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.predicates.AllOfCondition;
import net.minecraft.world.level.storage.loot.predicates.DamageSourceCondition;
import net.minecraft.world.level.storage.loot.predicates.LootItemCondition;
import net.minecraft.world.level.storage.loot.predicates.LootItemEntityPropertyCondition;
import net.neoforged.neoforge.common.Tags;


public class ModEnchantments {

    public static final ResourceKey<Enchantment> FEROCITY = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "ferocity"));
    public static final ResourceKey<Enchantment> VENOMOUS = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "venomous"));
    public static final ResourceKey<Enchantment> CLARITY = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "clarity"));
    public static final ResourceKey<Enchantment> KNOWLEDGE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "knowledge"));
    public static final ResourceKey<Enchantment> HARMFUL = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "harmful"));
    public static final ResourceKey<Enchantment> DULLNESS = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "dullness"));
    public static final ResourceKey<Enchantment> FROSTBITE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "frostbite"));
    public static final ResourceKey<Enchantment> VAMPIRISM = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "vampirism"));
    public static final ResourceKey<Enchantment> BUFFER = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "buffer"));
    public static final ResourceKey<Enchantment> LETHALITY = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "lethality"));
    public static final ResourceKey<Enchantment> RAPID_SLASH = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "rapid_slash"));
    public static final ResourceKey<Enchantment> IGNITE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "ignite"));
    public static final ResourceKey<Enchantment> ABLAZE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "ablaze"));
    public static final ResourceKey<Enchantment> FIERY = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "fiery"));
    public static final ResourceKey<Enchantment> BURNING = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "burning"));
    public static final ResourceKey<Enchantment> CONFLAGRATION = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "conflagration"));
    public static final ResourceKey<Enchantment> WATER_ASPECT = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "water_aspect"));
    public static final ResourceKey<Enchantment> SADISM = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "sadism"));
    public static final ResourceKey<Enchantment> BRUTALITY = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "brutality"));
    public static final ResourceKey<Enchantment> BLITZ = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "blitz"));
    public static final ResourceKey<Enchantment> DRAGGING = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "dragging"));
    public static final ResourceKey<Enchantment> ENERGY = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "energy"));
    public static final ResourceKey<Enchantment> FORCE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "force"));
    public static final ResourceKey<Enchantment> VOLLEY = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "volley"));
//    public static final ResourceKey<Enchantment> FLEET = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "fleet"));
    public static final ResourceKey<Enchantment> VITAE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "vitae"));
    public static final ResourceKey<Enchantment> BERSERKER = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "berserker"));
    public static final ResourceKey<Enchantment> ADV_PROTECTION = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "adv_protection"));
    public static final ResourceKey<Enchantment> ADV_PROJECTILE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "adv_projectile"));
    public static final ResourceKey<Enchantment> ADV_BLAST = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "adv_blast"));
    public static final ResourceKey<Enchantment> ADV_FIRE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "adv_fire"));
    public static final ResourceKey<Enchantment> RAGE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "rage"));
    public static final ResourceKey<Enchantment> HOLDING = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "holding"));
    public static final ResourceKey<Enchantment> ABIDE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "abide"));
    public static final ResourceKey<Enchantment> STEPPER = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "stepper"));
    public static final ResourceKey<Enchantment> RUSTING = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "rusting"));
    public static final ResourceKey<Enchantment> DOUBLE_JUMP = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "double_jump"));
    public static final ResourceKey<Enchantment> HIGH_JUMP = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "high_jump"));
    public static final ResourceKey<Enchantment> ARMOR_PENETRATION = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "armor_penetration"));
    public static final ResourceKey<Enchantment> STARE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "stare"));
    public static final ResourceKey<Enchantment> DEFTNESS = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "deftness"));
    public static final ResourceKey<Enchantment> EXTENT = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "extent"));
    public static final ResourceKey<Enchantment> ADEPT = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "adept"));
    public static final ResourceKey<Enchantment> VEIN_MINING = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "vein_mining"));
    public static final ResourceKey<Enchantment> SMELTER = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "smelter"));
    public static final ResourceKey<Enchantment> LIFESTEAL = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "lifesteal"));
    public static final ResourceKey<Enchantment> VOID_RESIDENT = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "void_resident"));
    public static final ResourceKey<Enchantment> HELL_RESIDENT = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "hell_resident"));
    public static final ResourceKey<Enchantment> GLOBE_RESIDENT = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "globe_resident"));
    public static final ResourceKey<Enchantment> COPY = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "copy"));
    public static final ResourceKey<Enchantment> VIPER = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "viper"));
    public static final ResourceKey<Enchantment> MAGNETIC = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "magnetic"));
    public static final ResourceKey<Enchantment> RESOLVE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "resolve"));
    public static final ResourceKey<Enchantment> SEA_PROSPERITY = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "sea_prosperity"));
    public static final ResourceKey<Enchantment> MAGIC_SIPHON = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "magic_siphon"));
    public static final ResourceKey<Enchantment> TOXIC = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "toxic"));
    public static final ResourceKey<Enchantment> LIVING_TORCH = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "living_torch"));

    public static final ResourceKey<Enchantment> AFFIX_ARMOR = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_armor"));
    public static final ResourceKey<Enchantment> AFFIX_ARMOR_TOUGHNESS = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_armor_toughness"));
    public static final ResourceKey<Enchantment> AFFIX_ATTACK_DAMAGE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_attack_damage"));
    public static final ResourceKey<Enchantment> AFFIX_ATTACK_SPEED = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_attack_speed"));
    public static final ResourceKey<Enchantment> AFFIX_BLOCK_BREAK_SPEED = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_block_break_speed"));
    public static final ResourceKey<Enchantment> AFFIX_BLOCK_INTERACTION_RANGE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_block_interaction_range"));
    public static final ResourceKey<Enchantment> AFFIX_ENTITY_INTERACTION_RANGE = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_entity_interaction_range"));
    public static final ResourceKey<Enchantment> AFFIX_JUMP_STRENGTH = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_jump_strength"));
    public static final ResourceKey<Enchantment> AFFIX_LUCK = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_luck"));
    public static final ResourceKey<Enchantment> AFFIX_MAX_HEALTH = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_max_health"));
    public static final ResourceKey<Enchantment> AFFIX_MINING_EFFICIENCY = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_mining_efficiency"));
    public static final ResourceKey<Enchantment> AFFIX_MOVEMENT_SPEED = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_movement_speed"));
    public static final ResourceKey<Enchantment> AFFIX_OXYGEN_BONUS = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_oxygen_bonus"));
    public static final ResourceKey<Enchantment> AFFIX_WATER_MOVEMENT_EFFICIENCY = ResourceKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_water_movement_efficiency"));


    public static void bootstrap(BootstrapContext<Enchantment> context) {
        var enchantments = context.lookup(Registries.ENCHANTMENT);
        var items = context.lookup(Registries.ITEM);
        var clarityExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/clarity_exclusive"));
        var healExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/heal_exclusive"));
        var aspectExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/aspect_exclusive"));
        var flameExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/flame_exclusive"));
        var damageExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/damage_exclusive"));
        var powerExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/power_exclusive"));
        var bowDrawExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/bowdraw_exclusive"));
        var protectionExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/protection_exclusive"));
        var maxHpExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/maxhp_exclusive"));
        var jumpExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/jump_exclusive"));
        var affixExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/affix_exclusive"));
        var efficiencyExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/efficiency_exclusive"));
        var luckExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/luck_exclusive"));
        var dmgBoostExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/dmgboost_exclusive"));
        var thornsExclusive = TagKey.create(Registries.ENCHANTMENT, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "set_exclusive/thorns_exclusive"));
        TagKey<EntityType<?>> waterVulnerable = TagKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "water_vulnerable"));
        TagKey<EntityType<?>> sadismVulnerable = TagKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "sadism_vulnerable"));
        TagKey<EntityType<?>> brutalityVulnerable = TagKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "brutality_vulnerable"));
////////////////COMMON 12////////////////
        register(context, HARMFUL, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 5, Enchantment.dynamicCost(5, 6), Enchantment.dynamicCost(36, 6), 2, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(damageExclusive)).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(0.75f, 0.25f))));
        register(context, ABIDE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 3, 1, Enchantment.dynamicCost(5, 6), Enchantment.dynamicCost(36, 6), 1, EquipmentSlotGroup.MAINHAND)));
        register(context, DULLNESS, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 4, Enchantment.dynamicCost(5, 6), Enchantment.dynamicCost(36, 6), 2, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(damageExclusive)).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(-2f, -0.5f))));
        register(context, ARMOR_PENETRATION, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 5, Enchantment.dynamicCost(3, 9), Enchantment.dynamicCost(36, 6), 2, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(damageExclusive)).withEffect(EnchantmentEffectComponents.ARMOR_EFFECTIVENESS, new AddValue(LevelBasedValue.perLevel(-0.3f, -0.3f))));
        register(context, IGNITE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 2, Enchantment.dynamicCost(5, 6), Enchantment.dynamicCost(36, 6), 2, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(aspectExclusive)).withEffect(EnchantmentEffectComponents.POST_ATTACK, EnchantmentTarget.ATTACKER, EnchantmentTarget.VICTIM, new Ignite(LevelBasedValue.perLevel(2f))));
        register(context, BURNING, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.BOW_ENCHANTABLE), items.getOrThrow(ItemTags.BOW_ENCHANTABLE), 5, 1, Enchantment.constantCost(8), Enchantment.constantCost(35), 1, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(flameExclusive)).withEffect(EnchantmentEffectComponents.PROJECTILE_SPAWNED, new Ignite(LevelBasedValue.constant(40f))));
        register(context, SADISM, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 5, Enchantment.dynamicCost(5, 6), Enchantment.dynamicCost(36, 6), 3, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(damageExclusive)).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(2f, 2f)), LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.THIS, EntityPredicate.Builder.entity().entityType(EntityTypePredicate.of(sadismVulnerable)))));
        register(context, DRAGGING, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.BOW_ENCHANTABLE), items.getOrThrow(ItemTags.BOW_ENCHANTABLE), 5, 2, Enchantment.dynamicCost(5, 6), Enchantment.dynamicCost(36, 6), 3, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(bowDrawExclusive)).exclusiveWith(enchantments.getOrThrow(powerExclusive)).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(3.25f, 1.75f))));
        register(context, ENERGY, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.BOW_ENCHANTABLE), items.getOrThrow(ItemTags.BOW_ENCHANTABLE), 5, 5, Enchantment.dynamicCost(5, 6), Enchantment.dynamicCost(36, 6), 1, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(powerExclusive)).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(0.25f, 0.25f))));
        register(context, RAGE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.CHEST_ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.CHEST_ARMOR_ENCHANTABLE), 5, 2, Enchantment.dynamicCost(5, 6), Enchantment.dynamicCost(36, 6), 2, EquipmentSlotGroup.CHEST)));
        register(context, SMELTER, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.MINING_ENCHANTABLE), items.getOrThrow(ItemTags.MINING_ENCHANTABLE), 4, 1, Enchantment.dynamicCost(5, 6), Enchantment.dynamicCost(36, 6), 2, EquipmentSlotGroup.MAINHAND)));
        register(context, VEIN_MINING, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.MINING_ENCHANTABLE), items.getOrThrow(ItemTags.MINING_ENCHANTABLE), 4, 1, Enchantment.dynamicCost(5, 6), Enchantment.dynamicCost(36, 6), 2, EquipmentSlotGroup.MAINHAND)));
////////////////UNCOMMON 10////////////////
        register(context, FROSTBITE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 3, Enchantment.dynamicCost(8, 6), Enchantment.dynamicCost(44, 6), 2, EquipmentSlotGroup.MAINHAND)).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(2F, 2F)), LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.THIS, EntityPredicate.Builder.entity().entityType(EntityTypePredicate.of(EntityTypeTags.FREEZE_IMMUNE_ENTITY_TYPES)))).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(2F, 2F)), LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.THIS, EntityPredicate.Builder.entity().entityType(EntityTypePredicate.of(EntityTypeTags.SKELETONS)))).withEffect(EnchantmentEffectComponents.POST_ATTACK, EnchantmentTarget.ATTACKER, EnchantmentTarget.VICTIM, new ApplyMobEffect(HolderSet.direct(MobEffects.MOVEMENT_SLOWDOWN), LevelBasedValue.constant(2F), LevelBasedValue.perLevel(2F, 2F), LevelBasedValue.constant(1F), LevelBasedValue.perLevel(1F, 1F))).withEffect(EnchantmentEffectComponents.POST_ATTACK, EnchantmentTarget.ATTACKER, EnchantmentTarget.VICTIM, new FrostbiteEnchantmentEffect()));
        register(context, VENOMOUS, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 3, Enchantment.dynamicCost(8, 6), Enchantment.dynamicCost(44, 6), 5, EquipmentSlotGroup.MAINHAND)).withEffect(EnchantmentEffectComponents.POST_ATTACK, EnchantmentTarget.ATTACKER, EnchantmentTarget.ATTACKER, new ApplyMobEffect(HolderSet.direct(MobEffects.POISON), LevelBasedValue.constant(3f), LevelBasedValue.perLevel(3f, 3f), LevelBasedValue.constant(1f), LevelBasedValue.perLevel(1f, 1f))));
        register(context, STEPPER, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.FOOT_ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.FOOT_ARMOR_ENCHANTABLE), 5, 1, Enchantment.dynamicCost(8, 6), Enchantment.dynamicCost(44, 6), 2, EquipmentSlotGroup.FEET)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "stepper"), Attributes.STEP_HEIGHT, new LevelBasedValue.Constant(0.5f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, DOUBLE_JUMP, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.FOOT_ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.FOOT_ARMOR_ENCHANTABLE), 3, 1, Enchantment.dynamicCost(8, 6), Enchantment.dynamicCost(44, 6), 2, EquipmentSlotGroup.FEET)).exclusiveWith(enchantments.getOrThrow(jumpExclusive)));
        register(context, VAMPIRISM, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 6, 2, Enchantment.dynamicCost(8, 6), Enchantment.dynamicCost(44, 6), 5, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(healExclusive)).withEffect(EnchantmentEffectComponents.POST_ATTACK, EnchantmentTarget.ATTACKER, EnchantmentTarget.ATTACKER, new ApplyMobEffect(HolderSet.direct(MobEffects.HEAL), LevelBasedValue.constant(1f), LevelBasedValue.constant(1f), LevelBasedValue.constant(1f), LevelBasedValue.constant(2f))));
        register(context, ABLAZE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 6, 2, Enchantment.dynamicCost(8, 6), Enchantment.dynamicCost(44, 6), 4, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(aspectExclusive)).withEffect(EnchantmentEffectComponents.POST_ATTACK, EnchantmentTarget.ATTACKER, EnchantmentTarget.VICTIM, new Ignite(LevelBasedValue.perLevel(6f))));
        register(context, FIERY, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.BOW_ENCHANTABLE), items.getOrThrow(ItemTags.BOW_ENCHANTABLE), 6, 1, Enchantment.constantCost(8), Enchantment.constantCost(65), 2, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(flameExclusive)).withEffect(EnchantmentEffectComponents.PROJECTILE_SPAWNED, new Ignite(LevelBasedValue.constant(160f))).withEffect(EnchantmentEffectComponents.PROJECTILE_SPAWNED, new FieryEnchantmentEffect()));
        register(context, WATER_ASPECT, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 6, 2, Enchantment.dynamicCost(8, 6), Enchantment.dynamicCost(44, 6), 4, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(aspectExclusive)).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(1f, 1f)), LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.THIS, EntityPredicate.Builder.entity().entityType(EntityTypePredicate.of(waterVulnerable)))).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(1.5f, 1.5f)), LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.THIS, EntityPredicate.Builder.entity().located(LocationPredicate.Builder.location().setFluid(FluidPredicate.Builder.fluid().of(Fluids.WATER))))).withEffect(EnchantmentEffectComponents.POST_ATTACK, EnchantmentTarget.ATTACKER, EnchantmentTarget.VICTIM, new FrostbiteEnchantmentEffect()));
        register(context, BRUTALITY, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 6, 5, Enchantment.dynamicCost(15, 10), Enchantment.dynamicCost(65, 10), 3, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(damageExclusive)).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(3f, 3f)), LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.THIS, EntityPredicate.Builder.entity().entityType(EntityTypePredicate.of(brutalityVulnerable)))));
        register(context, MAGNETIC, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.MINING_ENCHANTABLE), items.getOrThrow(ItemTags.MINING_ENCHANTABLE), 6, 1, Enchantment.dynamicCost(8, 6), Enchantment.dynamicCost(44, 6), 2, EquipmentSlotGroup.MAINHAND)));
////////////////RARE 12////////////////
        register(context, BUFFER, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 2, Enchantment.dynamicCost(16, 14), Enchantment.dynamicCost(70, 14), 4, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(healExclusive)).withEffect(EnchantmentEffectComponents.POST_ATTACK, EnchantmentTarget.ATTACKER, EnchantmentTarget.ATTACKER, new BufferEnchantmentEffect()));
        register(context, LIFESTEAL, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 2, Enchantment.dynamicCost(16, 14), Enchantment.dynamicCost(70, 14), 4, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(healExclusive)));
        register(context, STARE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.HEAD_ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.HEAD_ARMOR_ENCHANTABLE), 5, 1, Enchantment.dynamicCost(16, 14), Enchantment.dynamicCost(70, 14), 4, EquipmentSlotGroup.HEAD)));
        register(context, SEA_PROSPERITY, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.FISHING_ENCHANTABLE), items.getOrThrow(ItemTags.FISHING_ENCHANTABLE), 5, 3, Enchantment.dynamicCost(16, 14), Enchantment.dynamicCost(70, 14), 4, EquipmentSlotGroup.MAINHAND)).withEffect(EnchantmentEffectComponents.FISHING_LUCK_BONUS, new AddValue(LevelBasedValue.perLevel(3f))).exclusiveWith(enchantments.getOrThrow(luckExclusive)));
        register(context, KNOWLEDGE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 3, Enchantment.dynamicCost(16, 14), Enchantment.dynamicCost(70, 14), 4, EquipmentSlotGroup.MAINHAND)).withEffect(EnchantmentEffectComponents.MOB_EXPERIENCE, new AddValue(LevelBasedValue.perLevel(2.5f, 2.5f))));
        register(context, CLARITY, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 3, Enchantment.dynamicCost(16, 14), Enchantment.dynamicCost(70, 14), 4, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(clarityExclusive)).withEffect(EnchantmentEffectComponents.MOB_EXPERIENCE, new MultiplyValue(LevelBasedValue.perLevel(2f, 1f))));
        register(context, CONFLAGRATION, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 4, Enchantment.dynamicCost(16, 14), Enchantment.dynamicCost(70, 14), 4, EquipmentSlotGroup.MAINHAND)).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(1f, 0.75f)), LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.THIS, EntityPredicate.Builder.entity().flags(EntityFlagsPredicate.Builder.flags().setOnFire(true)))).exclusiveWith(enchantments.getOrThrow(dmgBoostExclusive)));
        register(context, VOLLEY, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.BOW_ENCHANTABLE), items.getOrThrow(ItemTags.BOW_ENCHANTABLE), 5, 4, Enchantment.dynamicCost(16, 7), Enchantment.dynamicCost(70, 14), 4, EquipmentSlotGroup.MAINHAND)).withEffect(EnchantmentEffectComponents.PROJECTILE_COUNT, new AddValue(LevelBasedValue.perLevel(1f, 1f))).withEffect(EnchantmentEffectComponents.PROJECTILE_SPREAD, new AddValue(LevelBasedValue.perLevel(1f))));
        register(context, ADEPT, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.MINING_ENCHANTABLE), items.getOrThrow(ItemTags.MINING_ENCHANTABLE), 5, 2, Enchantment.dynamicCost(16, 7), Enchantment.dynamicCost(70, 14), 4, EquipmentSlotGroup.MAINHAND)).withEffect(EnchantmentEffectComponents.BLOCK_EXPERIENCE, new AddValue(LevelBasedValue.perLevel(2.5f, 2.5f))));
        register(context, VIPER, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 5, 4, Enchantment.dynamicCost(16, 7), Enchantment.dynamicCost(70, 14), 4, EquipmentSlotGroup.MAINHAND)));
        register(context, TOXIC, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 5, 2, Enchantment.dynamicCost(16, 7), Enchantment.dynamicCost(70, 14), 4, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(thornsExclusive)));
        register(context, LIVING_TORCH, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 5, 2, Enchantment.dynamicCost(16, 7), Enchantment.dynamicCost(70, 14), 4, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(thornsExclusive)));
////////////////VERY RARE 10////////////////
        register(context, LETHALITY, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 3, 4, Enchantment.dynamicCost(20, 14), Enchantment.dynamicCost(70, 14), 6, EquipmentSlotGroup.MAINHAND)).withEffect(EnchantmentEffectComponents.ARMOR_EFFECTIVENESS, new AddValue(LevelBasedValue.perLevel(-0.1f, -0.1f))));
        register(context, HIGH_JUMP, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.FOOT_ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.FOOT_ARMOR_ENCHANTABLE), 3, 3, Enchantment.dynamicCost(20, 14), Enchantment.dynamicCost(70, 14), 6, EquipmentSlotGroup.FEET)).exclusiveWith(enchantments.getOrThrow(jumpExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "high_jump"), Attributes.SAFE_FALL_DISTANCE, new LevelBasedValue.Linear(2f, 2f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, ADV_PROTECTION, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 3, 4, Enchantment.dynamicCost(20, 14), Enchantment.dynamicCost(70, 14), 6, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(protectionExclusive)).withEffect(EnchantmentEffectComponents.DAMAGE_PROTECTION, new AddValue(LevelBasedValue.perLevel(1.5F)), DamageSourceCondition.hasDamageSource(DamageSourcePredicate.Builder.damageType().tag(TagPredicate.isNot(DamageTypeTags.BYPASSES_INVULNERABILITY)))));
        register(context, ADV_PROJECTILE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 3, 4, Enchantment.dynamicCost(20, 14), Enchantment.dynamicCost(70, 14), 6, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(protectionExclusive)).withEffect(EnchantmentEffectComponents.DAMAGE_PROTECTION, new AddValue(LevelBasedValue.perLevel(4.0F)), DamageSourceCondition.hasDamageSource(DamageSourcePredicate.Builder.damageType().tag(TagPredicate.is(DamageTypeTags.IS_PROJECTILE)).tag(TagPredicate.isNot(DamageTypeTags.BYPASSES_INVULNERABILITY)))).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "adv_projectile"), Attributes.KNOCKBACK_RESISTANCE, LevelBasedValue.perLevel(0.3F), AttributeModifier.Operation.ADD_MULTIPLIED_BASE)));
        register(context, ADV_BLAST, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 3, 4, Enchantment.dynamicCost(20, 14), Enchantment.dynamicCost(70, 14), 6, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(protectionExclusive)).withEffect(EnchantmentEffectComponents.DAMAGE_PROTECTION, new AddValue(LevelBasedValue.perLevel(4.0F)), DamageSourceCondition.hasDamageSource(DamageSourcePredicate.Builder.damageType().tag(TagPredicate.is(DamageTypeTags.IS_EXPLOSION)).tag(TagPredicate.isNot(DamageTypeTags.BYPASSES_INVULNERABILITY)))).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "adv_blast"), Attributes.EXPLOSION_KNOCKBACK_RESISTANCE, LevelBasedValue.perLevel(0.3F), AttributeModifier.Operation.ADD_VALUE)));
        register(context, ADV_FIRE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 3, 4, Enchantment.dynamicCost(20, 14), Enchantment.dynamicCost(70, 14), 6, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(protectionExclusive)).withEffect(EnchantmentEffectComponents.DAMAGE_PROTECTION, new AddValue(LevelBasedValue.perLevel(4.0F)), AllOfCondition.allOf(DamageSourceCondition.hasDamageSource(DamageSourcePredicate.Builder.damageType().tag(TagPredicate.is(DamageTypeTags.IS_FIRE)).tag(TagPredicate.isNot(DamageTypeTags.BYPASSES_INVULNERABILITY))))).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "adv_fire"), Attributes.BURNING_TIME, LevelBasedValue.perLevel(-0.3F), AttributeModifier.Operation.ADD_MULTIPLIED_BASE)));
        register(context, DEFTNESS, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.MINING_ENCHANTABLE), items.getOrThrow(ItemTags.MINING_ENCHANTABLE), 3, 5, Enchantment.dynamicCost(20, 14), Enchantment.dynamicCost(70, 14), 6, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(efficiencyExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "deftness"), Attributes.MINING_EFFICIENCY, new LevelBasedValue.Linear(10f,7.5f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, GLOBE_RESIDENT, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.LEG_ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.LEG_ARMOR_ENCHANTABLE), 3, 2, Enchantment.dynamicCost(20, 14), Enchantment.dynamicCost(70, 14), 6, EquipmentSlotGroup.LEGS)));
        register(context, VOID_RESIDENT, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.LEG_ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.LEG_ARMOR_ENCHANTABLE), 3, 2, Enchantment.dynamicCost(20, 14), Enchantment.dynamicCost(70, 14), 6, EquipmentSlotGroup.LEGS)));
        register(context, HELL_RESIDENT, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.LEG_ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.LEG_ARMOR_ENCHANTABLE), 3, 2, Enchantment.dynamicCost(20, 14), Enchantment.dynamicCost(70, 14), 6, EquipmentSlotGroup.LEGS)));
////////////////EPIC 10////////////////
        register(context, COPY, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.MINING_ENCHANTABLE), items.getOrThrow(ItemTags.MINING_ENCHANTABLE), 3, 3, Enchantment.dynamicCost(25, 15), Enchantment.dynamicCost(65, 12), 8, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(Tags.Enchantments.INCREASE_BLOCK_DROPS)));
        register(context, MAGIC_SIPHON, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 3, 5, Enchantment.dynamicCost(25, 15), Enchantment.dynamicCost(65, 12), 8, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(dmgBoostExclusive)));
        register(context, RESOLVE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.TOOLS_SHIELD), items.getOrThrow(Tags.Items.TOOLS_SHIELD), 3, 1, Enchantment.dynamicCost(25, 15), Enchantment.dynamicCost(65, 12), 8, EquipmentSlotGroup.OFFHAND)));
        register(context, EXTENT, Enchantment.enchantment(Enchantment.definition(items.getOrThrow((Tags.Items.TOOLS)), items.getOrThrow(Tags.Items.TOOLS), 3, 3, Enchantment.dynamicCost(25, 15), Enchantment.dynamicCost(65, 12), 8, EquipmentSlotGroup.MAINHAND)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "extent"), Attributes.BLOCK_INTERACTION_RANGE, new LevelBasedValue.Linear(1f, 0.5f), AttributeModifier.Operation.ADD_VALUE)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "extent"), Attributes.ENTITY_INTERACTION_RANGE, new LevelBasedValue.Linear(1f, 0.5f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, BLITZ, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.BOW_ENCHANTABLE), items.getOrThrow(ItemTags.BOW_ENCHANTABLE), 3, 4, Enchantment.dynamicCost(25, 15), Enchantment.dynamicCost(65, 12), 8, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(bowDrawExclusive)));
        register(context, VITAE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.CHEST_ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.CHEST_ARMOR_ENCHANTABLE), 3, 5, Enchantment.dynamicCost(25, 15), Enchantment.dynamicCost(65, 12), 8, EquipmentSlotGroup.CHEST)).exclusiveWith(enchantments.getOrThrow(maxHpExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "vitae"), Attributes.MAX_HEALTH, new LevelBasedValue.Linear(2f, 2.5f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, BERSERKER, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.CHEST_ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.CHEST_ARMOR_ENCHANTABLE), 3, 5, Enchantment.dynamicCost(25, 15), Enchantment.dynamicCost(65, 12), 8, EquipmentSlotGroup.CHEST)).exclusiveWith(enchantments.getOrThrow(maxHpExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "berserker"), Attributes.MAX_HEALTH, new LevelBasedValue.Linear(-2f, -1.75f), AttributeModifier.Operation.ADD_VALUE)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "berserker"), Attributes.ATTACK_DAMAGE, new LevelBasedValue.Linear(2f, 2f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, FEROCITY, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 3, 5, Enchantment.dynamicCost(25, 15), Enchantment.dynamicCost(65, 12), 8, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(EnchantmentTags.DAMAGE_EXCLUSIVE)).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(2f, 1f))));
        register(context, FORCE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.BOW_ENCHANTABLE), items.getOrThrow(ItemTags.BOW_ENCHANTABLE), 3, 5, Enchantment.dynamicCost(25, 15), Enchantment.dynamicCost(65, 12), 8, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(powerExclusive)).withEffect(EnchantmentEffectComponents.DAMAGE, new AddValue(LevelBasedValue.perLevel(0.75f, 0.75f))));
        register(context, RAPID_SLASH, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 3, 5, Enchantment.dynamicCost(25, 15), Enchantment.dynamicCost(65, 12), 8, EquipmentSlotGroup.MAINHAND)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "rapid_slash"), Attributes.ATTACK_SPEED, new LevelBasedValue.Linear(0.2F, 0.2f), AttributeModifier.Operation.ADD_VALUE)));
////////////////OTHER 16////////////////
//        register(context, FLEET, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.BOW_ENCHANTABLE), items.getOrThrow(ItemTags.BOW_ENCHANTABLE), 4, 4, Enchantment.dynamicCost(8, 10), Enchantment.dynamicCost(15, 10), 8, EquipmentSlotGroup.MAINHAND)));
        register(context, HOLDING, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.ANY)));
        register(context, RUSTING, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.ANY)));
        register(context, AFFIX_ARMOR, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_armor"), Attributes.ARMOR, new LevelBasedValue.Constant(1f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_ARMOR_TOUGHNESS, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_armor_toughness"), Attributes.ARMOR_TOUGHNESS, new LevelBasedValue.Constant(0.5f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_ATTACK_DAMAGE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_attack_damage"), Attributes.ATTACK_DAMAGE, new LevelBasedValue.Constant(0.5f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_ATTACK_SPEED, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), items.getOrThrow(Tags.Items.MELEE_WEAPON_TOOLS), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_attack_speed"), Attributes.ATTACK_SPEED, new LevelBasedValue.Constant(0.3f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_BLOCK_BREAK_SPEED, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.MINING_ENCHANTABLE), items.getOrThrow(ItemTags.MINING_ENCHANTABLE), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_block_break_speed"), Attributes.BLOCK_BREAK_SPEED, new LevelBasedValue.Constant(0.5f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_BLOCK_INTERACTION_RANGE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.TOOLS), items.getOrThrow(Tags.Items.TOOLS), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_block_interaction_range"), Attributes.BLOCK_INTERACTION_RANGE, new LevelBasedValue.Constant(1f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_ENTITY_INTERACTION_RANGE, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(Tags.Items.TOOLS), items.getOrThrow(Tags.Items.TOOLS), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_entity_interaction_range"), Attributes.ENTITY_INTERACTION_RANGE, new LevelBasedValue.Constant(1f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_JUMP_STRENGTH, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_jump_strength"), Attributes.JUMP_STRENGTH, new LevelBasedValue.Constant(0.5f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_LUCK, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_luck"), Attributes.LUCK, new LevelBasedValue.Constant(1.5f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_MAX_HEALTH, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_max_health"), Attributes.JUMP_STRENGTH, new LevelBasedValue.Constant(1f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_MINING_EFFICIENCY, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.MINING_ENCHANTABLE), items.getOrThrow(ItemTags.MINING_ENCHANTABLE), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.MAINHAND)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_mining_efficiency"), Attributes.MINING_EFFICIENCY, new LevelBasedValue.Constant(2f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_MOVEMENT_SPEED, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_movement_speed"), Attributes.MOVEMENT_SPEED, new LevelBasedValue.Constant(0.5f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_WATER_MOVEMENT_EFFICIENCY, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_water_movement_efficiency"), Attributes.WATER_MOVEMENT_EFFICIENCY, new LevelBasedValue.Constant(1f), AttributeModifier.Operation.ADD_VALUE)));
        register(context, AFFIX_OXYGEN_BONUS, Enchantment.enchantment(Enchantment.definition(items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), items.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 1, 1, Enchantment.constantCost(1), Enchantment.constantCost(1), 1, EquipmentSlotGroup.ARMOR)).exclusiveWith(enchantments.getOrThrow(affixExclusive)).withEffect(EnchantmentEffectComponents.ATTRIBUTES, new EnchantmentAttributeEffect(ResourceLocation.fromNamespaceAndPath(BriskofMagic.MODID, "affix_oxygen_bonus"), Attributes.OXYGEN_BONUS, new LevelBasedValue.Constant(2f), AttributeModifier.Operation.ADD_VALUE)));

    }

    public static void register(BootstrapContext<Enchantment> registry, ResourceKey<Enchantment> key, Enchantment.Builder builder) {
        registry.register(key, builder.build(key.location()));
    }
}
